### PR TITLE
Update document-viewer.js

### PR DESCRIPTION
**Pull request by linhnhifm**

### CODE REVIEW

**Comment by ammsa** [comment]
You can make the link open in a new tab by adding a target attribute. Something like this 

```suggestion
elm.attr("target", "_blank");
```
Would be a much easier solution.

**Comment by linhnhifm** [comment]
Oh I see. Thank you for the pointer. I will try this solution first.

**Comment by ammsa** [comment]
Instead of `content = content.link(content)`, you can just do 
```
content = `<a href="${content}" target="_blank">${content}</a>`;
```

**Comment by linhnhifm** [comment]
Oh I see. I will make the change. Thank you.

**Pull request merged**
