### PR TITLE
Make judging button sticky

### PR DESCRIPTION
**Pull request by ammsa**
This makes judging widget hold value of useful/relevant value once a judgment is made.

Should work in all interfaces.

### CODE REVIEW

**Comment by ammsa** [comment]
@XinyiYan @AVakiliT If any of you can quickly test/review this, I'd appreciate it. I'll merge if it works on your end.

**Comment by XinyiYan** [comment]
Some feedback:

1. On Search, if you open a document first and make judgement through that pop-up page, the buttons on the search result page are not updated unless you refresh the search page.

2. On Discovery, if you go to the previously reviewed document, the buttons are not colored.

**Comment by ammsa** [comment]
@XinyiYan Thanks! I fixed the search problem in d225cf6. The other one is working fine on my end, maybe clear the browser cache?

**Comment by ammsa** [comment]
Ah it only works after you refresh the page..

**Comment by ammsa** [comment]
It should work now after bda322c

**Review by XinyiYan — APPROVED** [review]
Works on my side

**Pull request merged**
