### PR TITLE
fetch_single_doc_in_review_mode

### PR DESCRIPTION
**Pull request by XinyiYan**
One problem is that the Judgement class does not have para_id. When in paragraph mode, the Summary section is empty

### CODE REVIEW

**Comment by ammsa** [comment]
The new view seems like a smaller version of `GetAllAJAXView` in the judgment view. We can probably use that instead. To get document ids, it seems more fitting to use a view from the judgment app and not the review app.

**Comment by XinyiYan** [comment]
Use `GetAllAJAXView` to get doc_ids

**Comment by ammsa** [comment]
> Use `GetAllAJAXView` to get doc_ids

I haven't tested it but if it works fine on your end I'll go ahead and merge it. Let me know

**Comment by XinyiYan** [comment]
> > Use `GetAllAJAXView` to get doc_ids
> 
> I haven't tested it but if it works fine on your end I'll go ahead and merge it. Let me know

Yes it's working on my end.

**Pull request merged**
