### PR TITLE
Fix restoring session script

### PR DESCRIPTION
**Pull request by ammsa**
+ Fix restoring session script
   * This allows CAL in-memory sessions to be restored.
+ Fix importing topics script

Need to run `docker-compose build web` for docker to use the updated `start.sh`.

### CODE REVIEW

**Comment by ammsa** [comment]
@XinyiYan I remember you mentioning getting errors when you go the the discovery interface. This should fix that problem. 
If you can verify that it works, that would be great.

**Comment by XinyiYan** [comment]
still got errors when I activated an old session and then go to the discovery page. Discovery page only loads properly when I started a new session.  
--------------Error-----------
{"readyState":4,"responseText":"{\"message\": \"Ops! CALError.\"}","responseJSON":{"message":"Ops! CALError."},"status":404,"statusText":"Not Found"}

**Comment by ammsa** [comment]
The logs in the web container should tell you if there was an attempt to restore the sessions. Can you show me the web logs?

**Comment by ammsa** [comment]
I'll merge this for now, and later create another ticket to fix this problem.

**Pull request merged**
